include constants.makefile

EXE = laser-game.$(EXE_EXTENSION)

SRCS = \
	main.cpp \
	sequencer.cpp \
	utils.cpp \
	globals.cpp

OBJS = $(SRCS:%.cpp=%.o)

LDLIBS = -lopencv_core

include generic-rules.makefile


